location /recipe_chatbot_app/ {
    set $upstream http://recipe_chatbot_app:80;
    rewrite ^/recipe_chatbot_app/(.*)$ /$1 break;
    proxy_pass $upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location = /recipe_chatbot_app {
    return 301 /recipe_chatbot_app/;
}

location / {
    set $upstream http://recipe_chatbot_app:80;
    proxy_pass $upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
